import type { ExtractedDocument } from "@/lib/ai/document/document-types";
import { getActiveAIProvider, type QuestionOptions, type QuestionResult } from "@/lib/ai/providers";

/**
 * Generates questions based on document text using the active AI provider.
 */
export async function generateDocumentQuestions(
  doc: ExtractedDocument,
  options?: QuestionOptions,
): Promise<QuestionResult> {
  const provider = getActiveAIProvider();
  return provider.generateQuestions(doc, options);
}

/**
 * Formats generated questions into a comprehensive study / test paper.
 */
export function formatQuestionsAsText(result: QuestionResult, filename: string): string {
  const lines: string[] = [];
  lines.push(`================================================================`);
  lines.push(`DOCLY PRACTICE QUESTIONS & STUDY EXAM`);
  lines.push(`Source Document: ${filename}`);
  lines.push(`Total Questions: ${result.questions.length}`);
  lines.push(`Date: ${new Date().toLocaleString()}`);
  lines.push(`================================================================\n`);

  if (result.summary) {
    lines.push(`Description: ${result.summary}\n`);
  }

  // Part 1: Questions
  lines.push(`--- SECTION A: QUESTIONS ---\n`);
  result.questions.forEach((q, idx) => {
    lines.push(`Q${idx + 1}. [${q.type.toUpperCase()}] ${q.question}`);
    if (q.sourcePage) {
      lines.push(`    (Source: Page ${q.sourcePage})`);
    }

    if (q.type === "mcq" && q.options && q.options.length > 0) {
      const letters = ["A", "B", "C", "D"];
      q.options.forEach((opt, optIdx) => {
        lines.push(`    ${letters[optIdx] || "•"}. ${opt}`);
      });
    }
    lines.push("");
  });

  // Part 2: Answer Key & Explanations
  lines.push(`================================================================`);
  lines.push(`--- SECTION B: ANSWER KEY & EXPLANATIONS ---`);
  lines.push(`================================================================\n`);

  result.questions.forEach((q, idx) => {
    lines.push(`Q${idx + 1}: ${q.question}`);

    if (q.correctAnswer) {
      lines.push(`  Correct Answer: ${q.correctAnswer}`);
    }

    if (q.explanation) {
      lines.push(`  Explanation: ${q.explanation}`);
    }

    if (q.expectedAnswerPoints && q.expectedAnswerPoints.length > 0) {
      lines.push(`  Expected Key Points:`);
      for (const pt of q.expectedAnswerPoints) {
        lines.push(`    • ${pt}`);
      }
    }

    if (q.sourcePage) {
      lines.push(`  Verified Source: Page ${q.sourcePage}`);
    }

    lines.push("");
  });

  lines.push(`================================================================`);
  lines.push(`Generated by Docly AI Document Toolbox.`);
  lines.push(`================================================================`);

  return lines.join("\n");
}
